require('dotenv').config()
const mongoose = require('mongoose')
const authenticateUser = require('./authenticateUser')
const retrievePost = require('./retrievePost')

mongoose.connect(process.env.MONGOOSE_URL_TEST)
    .then(() => authenticateUser('gollum@eriador.com', 'tesoro'))
    .then((userId) => retrievePost(userId, '64bbcfc6e5ffe565ed8947aa'))
    .then(post => console.log(post))
    .catch(error => console.error(error))
    .finally(() => mongoose.disconnect())