require('dotenv').config()
const mongoose = require('mongoose')
const authenticateUser = require('./authenticateUser')
const toggleFavPost = require('./toggleFavPost')

mongoose.connect(process.env.MONGOOSE_URL_TEST)
    .then(() => toggleFavPost('64bbbbc2cd310235705c35e5', '64bbc488790a4db6ce056718'))
    .then(() => console.log('Favorite toggle Ok'))
    .catch(error => console.error(error))
    .finally(() => mongoose.disconnect())