require('dotenv').config()
const mongoose = require('mongoose')
const registerUser = require('./registerUser')

mongoose.connect(process.env.MONGOOSE_URL)
    .then(() => registerUser('Frodo Bolson', 'frodo@bolson-cerrado.com', 'mitril'))
    .then(() => registerUser('Bilbo Bolson', 'bilbo@bolson-cerrado.com', 'dardo'))
    .then(() => registerUser('Meriadoc Brandigamo', 'merry@comarca.com', 'rohan'))
    .then(() => registerUser('Peregrin Tuk', 'pippin@comarca.com', 'gondor'))
    .catch(error => console.error(error))
    .finally(() => mongoose.disconnect())